name: Hello from local action
on: workflow_dispatch
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        with:
          who-to-greet: "Mona the Octocat - $SECRET"
      - name: Last step
        run: echo "hi $SECRET"
